name: FTP Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: FTP deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 82.180.143.67               # ✅ No "ftp."
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: 
